[package]
name = "spawn_cell_egui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
eframe = "0.25"
winres = "0.1"
winapi = { version = "0.3", features = ["winuser", "windef"] }

[build-dependencies]
winres = "0.1"

